### ISSUE TITLE
"hard float" version of Raspbian "wheezy" no longer available on link provided

### ISSUE THREAD

**Issue by julietaSpace** [openframeworks/ofSite#270]
The page "Getting your Raspberry Pi ready for openFrameworks" appears to be dated

On this link:
"Install the latest Raspbian "wheezy" image from the Raspberry Pi downloads page"

... there is no option available for download other than "Debian"
"Make sure you are working with the the "hard float" version of Raspbian "wheezy", not the soft-float version (aka "Soft-float Debian "wheezy")."

**Comment by tpltnt** [comment]
@julietaSpace you can use the default Raspian (Debian Wheezy) image from https://www.raspberrypi.org/downloads/. This image is based on the hard float version of Debian. Some packages have a ":hf" suffix, which hints at that fact. I proposed a change to remove the confusing hint. Thank you for pointing at the issue!
