### ISSUE TITLE
ofFbo::bind() note

### ISSUE THREAD

**Issue by micuat** [openframeworks/ofSite#275]
I'm wondering if [ofFbo::bind()](http://openframeworks.cc/documentation/gl/ofFbo.html#show_bind) needs a notice that it is completely different from texture mapping that can be achieved by `ofFbo::getTextureReference().bind()`. (Implementation is discussed [here](https://github.com/openframeworks/openFrameworks/issues/1359) )

**Comment by arturoc** [comment]
Closed by #360
