### ISSUE TITLE
some 'edit class' links are broken

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/ofSite#285]
http://www.openframeworks.cc/documentation/ofxGui/ofxPanel.html

**Comment by tpltnt** [comment]
The problem seems to be a missing "addons" in the edit URL (...cc/documentation/**addons**/ofxG...).
To anyone taking this on: The page is generated via blogofile. Look at the code in the _tools directory to see how stuff is fiddled together.

**Comment by javl** [comment]
The addon name is checked against a list of known addons. If it is in the list, the **addons** parts is added to the URL. The list to check against is generated by the `list_all_addons()` function in [markdown_file.py](https://github.com/openframeworks/ofSite/blob/master/_tools/markdown_file.py) by going through the *_documentation/addons* folder.

But for instance [ofxAndroidapp](http://openframeworks.cc/documentation/ofxAndroid/ofxAndroidApp.html) has a folder in there called [ofxAndroid](https://github.com/openframeworks/ofSite/tree/master/_documentation/addons/ofxAndroid), as it's part of that addon, not *ofxAndroidapp*.
So the scripts should check for existence of its parent class or something similar.
