### ISSUE TITLE
Old wiki is down

### ISSUE THREAD

**Issue by workergnome** [openframeworks/ofSite#300]
http://wiki.openframeworks.cc/index.php no longer resolves.  There's still some useful content there that should be extracted if possible, and then the domain could be redirected to github?

**Comment by bilderbuchi** [comment]
ping @kylemcdonald . should we nuke the old wiki, as extracting that old content (what is it specifically, anyway, that's that valuable) probably won't happen any time soon.

**Comment by ofZach** [comment]
this is the change, FYI -- I looked on rackspace, it appears this is still on the old server however: 
ttp://www.mediawiki.org/wiki/Thread:Project:Support_desk/PHP_and_Mysql_was_upgraded_on_my_server_and_now_I_get_a_blank_white_page./reply

I wouldn't mind getting a backup of content, even if there is a lot of spam. for several years we recorded workshops and meetings via wiki, there's some good historical info at least.

**Comment by kylemcdonald** [comment]
i mentioned this to @ofTheo a while ago who knows more about the configuration but i don't think he's had a chance to download it yet. i agree it would be good to have it archived for historical reasons.

**Comment by ofTheo** [comment]
Wiki is back up. I just upgraded the mediawiki to the latest version. 
I THINK everything is how it used to be. Give me a shout if I missed anything.

**Comment by bilderbuchi** [comment]
Question: why don't we keep it hidden? It is full of old/outdated information, and people stumbling over this will just ge confused.
also, [this](https://github.com/openframeworks/openFrameworks/wiki/Old-Wiki-Analysis) may be useful for whoever will trawl the old wiki for information.

**Comment by workergnome** [comment]
I think the plan is to get rid of it--this just lets me get access to it to extract all the useful information from it first.

**Comment by ofTheo** [comment]
@workergnome do you need a dump of the database - whats the best way to get you access?

**Comment by workergnome** [comment]
I've done the extraction:  [of_wiki_dump](https://www.dropbox.com/s/080ftgxn5kfqo3m/of_wiki_dump.zip?dl=0) should contain the complete content of the site.  There's a scraped version of the site, preserving formatting, there's a collection of all the images (manually downloaded), and there's the original text for each of the files (named as markdown files, but not yet converted.) 

I did not save the discussion pages—a cursory look said that they weren't really used.

I also did not extract the original mediawiki source for pages that I thought were trivial and no longer relevant—sandbox pages, tutorials without actual content, etc.  We have the HTML page for them if needed.

@ofTheo, the only thing that might be useful would be a saved version of the images directory off the server—I have the images that appear on the page, but a couple pages used markup that had larger-res versions of them linked, and I did not follow those links.  

At this point, I think it would be fine to remove <wiki.openframeworks.cc> and redirect it to <https://github.com/openframeworks/openFrameworks/wiki>.

**Comment by ofTheo** [comment]
@workergnome here are the images folder as a zip if that helps: http://wiki.openframeworks.cc/images.zip

**Comment by workergnome** [comment]
Rockin'.  At this point, I think between these two links we have the complete wiki preserved.  Shut 'er down.

**Comment by ofTheo** [comment]
thanks! just added the redirect

**Comment by workergnome** [comment]
:+1:!

**Comment by kylemcdonald** [comment]
good call on the redirect.

also, some really good stuff in those images, including this classic one from @tchoi8

![workshop](https://cloud.githubusercontent.com/assets/157106/7653005/a83931ee-fb12-11e4-8671-09b72c105037.png)
