### ISSUE TITLE
login credentials not protected for forum

### ISSUE THREAD

**Issue by tpltnt** [openframeworks/ofSite#324]
The forum hosted at http://forum.openframeworks.cc/ does not support TLS/SSL. The forum also requires passwords as authentication tokens. Due to the lack of encryption, the sensitive information of transmitted in clear text making it vulnerable to sniffing and manipulation. Not protecting at least the login process is not a good practice to put it mildly. Having a properly TLS/SSL infrastructure (i.e. valid certificate) in place would fix this.

**Comment by kylemcdonald** [comment]
great point, hopefully no one is reusing passwords but in case they are we should follow a process like this https://meta.discourse.org/t/allowing-ssl-for-your-discourse-docker-setup/13847 to fix that

**Comment by arturoc** [comment]
i added an ssl certificate some months ago and the forum now runs completely under https
