### ISSUE TITLE
http://openframeworks.cc/ofBook/ forwards to http://openframeworks.cc/ofBook/chapters/toc.html ...

### ISSUE THREAD

**Issue by bakercp** [openframeworks/ofSite#344]
... which shows the home page.

@arturoc

**Comment by kylemcdonald** [comment]
i can make this change too, but i just realized i don't have access to ofSite directly right now. @arturoc @ofTheo if you could run on the server `curl https://github.com/kylemcdonald.keys | sed -e '$a\' >> ~/.ssh/authorized_keys` to give me access, that'd be great.
