### ISSUE TITLE
nightlies disappeared

### ISSUE THREAD

**Issue by bakercp** [openframeworks/ofSite#352]
@arturoc 

![openframeworks](https://cloud.githubusercontent.com/assets/300484/10545424/4a40e30c-73ee-11e5-860c-51b54fae4c68.png)

**Comment by arturoc** [comment]
i know i had to reinstall the server from scratch yesterday, it's almost working now.

**Comment by bakercp** [comment]
Ugh. Sorry you had to do that. Thanks for your hard work as always!
