### ISSUE TITLE
[REQUEST] inclusion of openFrameworks tutorial video series

### ISSUE THREAD

**Issue by lewislepton** [openframeworks/ofSite#357]
howdy all,

not an issue, just a request if someone is free and has the time and the things installed to run ofSite locally.

i would like if my openFrameworks tutorial series is put into the tutorials page. i dont know if you would want each video posted, or if you just need the link to the playlist and the link to the source code location from the series.
just think it would be a nice addition to the site to get new users into it if they see the videos available. people search on youtube, but good if all bases are looked into ;)

main playlist link
```
https://www.youtube.com/playlist?list=PL4neAtv21WOmrV8z9rSzL20QpdLU1zJLr
```

main source code link
```
https://github.com/lewislepton/openFrameworksTutorialSeries
```

if possible, the author name is `lewis lepton` and if you want my site link its `lewislepton.com` ;)

many thanks

**Comment by kylemcdonald** [comment]
hey lewis!

this would be great.

one way to do it is just have the link to the playlist, as you mention.

a more complete way might be to create a page that has all the titles and a short description of each, with a link to the video. this would be more work, and you'd have to maintain it when you add a new video, but it could be better for people searching?

i lean towards the first option since it will need the least work. if you want to submit a PR with your link added, that would be great!

**Comment by lewislepton** [comment]
hey @kylemcdonald 

yeah. i even tried doing the seperate videos on my site, but really its just more work. id rather code ;)
maybe down the road i will do a page with everything in, with descriptions. but thats later ;)

my PR thing [please feel free to edit] - some taken from my own site
---
this video series is for beginners, but also for people to brush up skills. rather than being 20+ minute videos, these are short & bite sized - to be easier & much better to take in. plus much easier for people to find what they need to learn from.

#VIEW VIDEOS & CODE
all videos are viewable from my super duper awesome cool spot youtube channel.
https://www.youtube.com/playlist?list=PL4neAtv21WOmrV8z9rSzL20QpdLU1zJLr

all source code with the projects we make are available from github
https://github.com/lewislepton/openFrameworksTutorialSeries

#FEATURES
• short & simple videos<br>
• source code available<br>
• easy for beginners  great for people to brush up on skills

**Comment by edap** [comment]
hey @lewislepton @kylemcdonald , i can take care of this

**Comment by lewislepton** [comment]
@edap ooooh. thank you very much. i dont have anything installed. pretty clean here ;)

so many thanks. you can maybe look at my spelling/gramer since im dislecic and things can just sound... odd to people ;)

**Comment by edap** [comment]
@lewislepton  @arturoc PR opened! https://github.com/openframeworks/ofSite/pull/359
