### ISSUE TITLE
Dead link in tutorial

### ISSUE THREAD

**Issue by javl** [openframeworks/ofSite#378]
The `openFrameworks for Processing users` page ([here on the website](http://openframeworks.cc/tutorials/first%20steps/002_openFrameworks_for_processing_users.html) and [here on github](https://github.com/openframeworks/ofSite/blob/master/_tutorials/02_first%20steps/002_openFrameworks_for_processing_users.markdown)) links to an external page which should contain more information about structs, but the linked page is dead.

See the `Structs, what are they for, and how can we use them?` part on the page. The linked external page is http://richardbowles.tripod.com/cpp/linklist/linklist.htm

**Comment by nebgnahz** [comment]
One possible simple fix is to use Internet Archive: https://web.archive.org/web/20090210180825/http://richardbowles.tripod.com/cpp/linklist/linklist.htm

An alternative is to use another tutorial on linked-list:
http://www.cprogramming.com/tutorial/lesson15.html

Personally inclined to go with the first option.
