### ISSUE TITLE
Typos on Linux Install page

### ISSUE THREAD

**Issue by javl** [openframeworks/ofSite#379]
There are a couple of misspelled words on in the Linux Install page. I wasn't able to find this specific page in the fork of ofSite so I couldn't fix it myself.
`dsitro_name` > `distro_name`
`scritps` > `scripts` (multiple times)

**Comment by arturoc** [comment]
this should be the file if you want to fix it:

https://github.com/openframeworks/ofSite/blob/master/setup/linux-install/index.html.mako

**Comment by javl** [comment]
This was fixed in 58a2915 & 73c4d5e.
