### ISSUE TITLE
tutorial translation not working

### ISSUE THREAD

**Issue by icq4ever** [openframeworks/ofSite#407]
## in tutorials folder, I added a new .ko.markdown file. but seems that not working with this file.

*projectGenerator document : original vs korean*
![screenshot from 2016-01-22 17 24 24](https://cloud.githubusercontent.com/assets/530796/12505767/19c9a13c-c12d-11e5-90f0-9a13ac0b8c7f.png)

*result in browser*
![screenshot from 2016-01-22 14 59 47](https://cloud.githubusercontent.com/assets/530796/12503659/9d11eedc-c119-11e5-9c29-4ae77f735146.png)

## image links are broken in translated page.

*broken img links in translated pages*. check the screenshot.
![screenshot from 2016-01-22 15 10 16](https://cloud.githubusercontent.com/assets/530796/12503715/486bf0e8-c11a-11e5-8db1-e722c2cc7da2.png)

**Comment by arturoc** [comment]
can you send a PR with a couple of translations of tutorails so i can check what's going on?

thanks!

**Comment by arturoc** [comment]
this is fixed now right?

**Comment by icq4ever** [comment]
no. still not working. have you tried with local server ?

**Comment by arturoc** [comment]
can you try if changing the image links to /tutorials/01_introduction/002_projectgenerator/img.png works? we might need to find a better way to solve it though
