### ISSUE TITLE
build system: build with pyenv-virtualenv

### ISSUE THREAD

**Issue by mactkg** [openframeworks/ofSite#412]
When building with python that is managed by [`pyenv`](https://github.com/yyuu/pyenv) and [`pyenv-virtualenv`](https://github.com/yyuu/pyenv-virtualenv), some scripts to build are don't work correctly.
Because [`pyenv-virtualenv`](https://github.com/yyuu/pyenv-virtualenv) change environment automatically, so `activate`/`deactivate` commands such as `source nikola/bin/activate` are not required but also caused error.

I think some build scripts have to switch call `source nikola/in/activate` and `deactivate`, but I have no idea to get information what environment is used.

I show a list of modify required scripts.

- https://github.com/openframeworks/ofSite/blob/master/build.sh
- https://github.com/openframeworks/ofSite/blob/master/auto_build.sh
- https://github.com/openframeworks/ofSite/blob/master/build_server.sh
- https://github.com/openframeworks/ofSite/blob/master/serve.sh

thanks

**Comment by arturoc** [comment]
the idea about those scripts is that then you don't need to start virtualenv your self. if you want to use virtualenv manually then you can just not use those scripts and call directly the nikola command

**Comment by mactkg** [comment]
thanks @arturo, I'm just wondering if there is people who use this
repo with same environment.
but the people will refer this issue, so we don't have to improve the
scripts now.

>

-- 
原 健太
明治大学総合数理学部 先端メディアサイエンス学科 渡邊研究室

090-1104-8196
mactkg@gmail.com
