### ISSUE TITLE
increase in 404 pages

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofSite#420]
this might be fixed but google webmaster tools just sent an "increase in 404 pages" emails, here's a CSV of the pages that gave 404s (it looks to be mostly from the files folder and the documentation pages which I know were recently fixed).  At any rate if it's helpful, here's the CSV which might help identify any issues with the site: 

https://dl.dropboxusercontent.com/u/92337283/misc/openframeworks-cc_20160127T135849Z_CrawlErrors.csv

**Comment by arturoc** [comment]
thanks, just copied the remaining files from the old server
