### ISSUE TITLE
Fixing broken links + i18n

### ISSUE THREAD

**Issue by stroborobo** [openframeworks/ofSite#425]
Hi there,

I just started to fix all those broken links and removing hard coded host names in links etc.. While doing so I noticed that many pages are available on the english pages but not on the Korean/Japanese versions. Should I just ignore them? They seem to be very outdated anyway.

What I was about to do:
- Replacing `http://www.openframeworks.cc/` with `/`
- Remove the `www.`  from `www.openframeworks.(cc|kr|jp)`
- Replace the old tutorial links with new new numbered ones (still TODO)

So what do you think? Removing the hostnames would also make some Korean/Japanese sites contain links that point to local sites that don't exist in that language.

**Comment by stroborobo** [comment]
```
bo-mbp:bo [~/src/ofSite]I> g s | grep '\.ko\.'
 M content/community.ko.md
 M content/download.ko.md
 M content/older.ko.md
 M content/setup/raspberrypi/Raspberry-Pi-Getting-Started-Wheezy.ko.md
 M content/setup/raspberrypi/Raspberry-Pi-Getting-Started.ko.md
 M tutorials/01_introduction/000_introduction.ko.asciidoc
 M tutorials/01_introduction/001_chapter1.ko.asciidoc
 M "tutorials/02_first steps/001_My_first_particle_system.ko.markdown"
 M "tutorials/02_first steps/002_openFrameworks_for_processing_users.ko.markdown"
 M "tutorials/02_first steps/003_ooops_object_oriented_programming.ko.markdown"
 M tutorials/02_maths/001_vector_maths.ko.markdown
 M tutorials/03_graphics/generativemesh.ko.markdown
 M tutorials/10_developers/003_contributing_to_the_documentation.ko.markdown
 M "tutorials/11_c++ concepts/001_stl_vectors_basic.ko.markdown"
bo-mbp:bo [~/src/ofSite]I> g s | grep '\.ja\.'
 M content/community.ja.md
bo-mbp:bo [~/src/ofSite]I>
```

That's not too much, I'll just check them manually now.

**Comment by stroborobo** [comment]
Also noticed now that the Korean page has moved links in the Korean documentation category introductions are pointing to Korean documentation pages that don't exist and go 404.

E.g. in `documentation/3d/introduction.markdown`: [Link](http://openframeworks.cc/ko/documentation/3d/) see the ofMesh link.

**Comment by arturoc** [comment]
oh, ok thanks, i'll take a look

**Comment by stroborobo** [comment]
Just a thought: maybe we could migrate the documentation to a software made for presenting documentation. Like the [MDN](https://developer.mozilla.org/en-US/), it works really well, this specifically is probably overkill for us, but something like that. All the i18n is already implemented and working really well.

I don't know anything about Nikola and haven't really looked into ofSite's build yet, so this might be total bogus.

**Comment by stroborobo** [comment]
Hm, seems harder than I thought to find a documentation generator that supports nice localisation... Didn't find a good one in the last 30 minutes at least.

**Comment by arturoc** [comment]
yeah i'm not sure we should have localization for the docs,  it wouldn't be to hard to implement really as it is now but unless someone is willing to translate the docs i won't do it. i don't think it's a good idea to complicate the code unless we need to
