### ISSUE TITLE
Linux codeblocks site broken

### ISSUE THREAD

**Issue by stroborobo** [openframeworks/ofSite#426]
http://openframeworks.cc/setup/linux-codeblocks/

There's a .mako file in there, shouldn't that be a .md file? Doesn't get built by `./build.sh`

**Comment by arturoc** [comment]
codeblocks is deprecated now so we don't have docs for it anymore, if there's a mako it shouldn't be there :), where is it?

**Comment by arturoc** [comment]
i mean not officially supported any more by OF not that codeblocks is deprecated itself

**Comment by stroborobo** [comment]
It's `/files/setup/linux-codeblocks/index.html.mako`

And linked to in these:

- `/tutorials/01_introduction/000_introduction.asciidoc`
- `/tutorials/01_introduction/000_introduction.ko.asciidoc`

Should I remove those links and the file while I'm at it?

**Comment by arturoc** [comment]
yes thanks!

**Comment by stroborobo** [comment]
Ok, then I'll consider that part of #425 :)
