### ISSUE TITLE
some tutorials author information are not working

### ISSUE THREAD

**Issue by icq4ever** [openframeworks/ofSite#432]
asciidoc tutorials's author information is not generated normally.
instead, it saids, openframeworks.

check these pages : [introduction](http://openframeworks.cc/tutorials/01_introduction/000_introduction/), [getting started](http://openframeworks.cc/tutorials/01_introduction/001_chapter1/)

**Comment by arturoc** [comment]
i know, i've seen that but haven't find a way to fix it. i want to port the 2 asciidoc tutorials we have to markdown since it's much better supported and doesn't require to install any external binary

**Comment by edap** [comment]
I can take care of moving to markdown the `01_introduction` folder

**Comment by arturoc** [comment]
that would be great. it's only the 000 and 001 tutorials, 002, the one about the project generator is already in markdown. thanks!
