### ISSUE TITLE
translation of new learning section

### ISSUE THREAD

**Issue by arturoc** [openframeworks/ofSite#484]
mostly for @tado and @icq4ever but also eveybody else who has helped translating.

During the docsprint that has been going on this weekend some people have been working on changing the old tutorials section into a new learning one.

there's now a learning folder which works the same as the old tutorials section (i've leave it there by now so we can move translations easily.)

By now you can translate the messages in https://github.com/openframeworks/ofSite/blob/master/messages/

I've added the new ones at the end of the japanese and korean localization files there's really only a few of them so that should be really easy to translate.

The new tutorials can be translated the same way as before, just add a .ko.markdown or .ja.markdown with the same title and the translated text and the page will automatically pick up the new ones right away.

Then there's the book, some of the old tutorials, for which there was translation are now part of the book which is not part of the web system so those translations are not shown anymore right now. 

Would you be willing to translate the parts of the book that are not still translated at some point? if so i can make the book render through the web system so we can also get localization for it and get an autogenerated index in all the languages. Otherwise we can just leave it as it is or i can add the sections titles to the messages files so at least the index can be translated but that would probably be confusing.

We wouldn't even need to translate everything but since there's already a few chapters (the ones that were tutorials before) that were already translated it would be great to get your opinion on what you want to do with them.

**Comment by icq4ever** [comment]
huge update! :D 
I'll update documents..
by the way.. now ofBook pages only english pages served.. I'll add korean version of TOC (learning/of_book.ko.md). with no modification link addresses.

**Comment by tado** [comment]
Thanks arturo!

I will translate new learning section index and new tutorial documents one
by one.




On Sun, Feb 21, 2016 at 9:16 PM, arturo <notifications@github.com> wrote:

> mostly for @tado <https://github.com/tado> and @icq4ever
> <https://github.com/icq4ever> but also eveybody else who has helped
> translating.
>
> During the docsprint that has been going on this weekend some people have
> been working on changing the old tutorials section into a new learning one.
>
> there's now a learning folder which works the same as the old tutorials
> section (i've leave it there by now so we can move translations easily.)
>
> By now you can translate the messages in
> https://github.com/openframeworks/ofSite/blob/master/messages/
>
> I've added the new ones at the end of the japanese and korean localization
> files there's really only a few of them so that should be really easy to
> translate.
>
> The new tutorials can be translated the same way as before, just add a
> .ko.markdown or .ja.markdown with the same title and the translated text
> and the page will automatically pick up the new ones right away.
>
> Then there's the book, some of the old tutorials, for which there was
> translation are now part of the book which is not part of the web system so
> those translations are not shown anymore right now.
>
> Would you be willing to translate the parts of the book that are not still
> translated at some point? if so i can make the book render through the web
> system so we can also get localization for it and get an autogenerated
> index in all the languages. Otherwise we can just leave it as it is or i
> can add the sections titles to the messages files so at least the index can
> be translated but that would probably be confusing.
>
> We wouldn't even need to translate everything but since there's already a
> few chapters (the ones that were tutorials before) that were already
> translated it would be great to get your opinion on what you want to do
> with them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/ofSite/issues/484>.
>



-- 
田所 淳 (たどころ あつし)

**Comment by arturoc** [comment]
@icq4ever yes that's what i meant, ofBook now works in english only. If you think you want to translate it i can look into rendering it using the web system.

**Comment by tado** [comment]
@arturo, Yes! I want to translate ofBook in Japanese. I asked people in oF
community of Japan to help ofBook translation, some people proffer help to
translate.

On Mon, Feb 22, 2016 at 6:40 PM, arturo <notifications@github.com> wrote:

> @icq4ever <https://github.com/icq4ever> yes that's what i meant, ofBook
> now works in english only. If you think you want to translate it i can look
> into rendering it using the web system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/ofSite/issues/484#issuecomment-187096193>
> .
>



-- 
田所 淳 (たどころ あつし)

**Comment by arturoc** [comment]
great!, let me coordinate with the people who have been working in the design of the book so we can find the least disruptive way to do it for everyone.

In any case if someone want to start translating the same format as the web is good, just create one file with the .ja.md or .ko.md for every .md in the english version.

as i said there's some things that are already translated because they were old tutorials and those are still in the tutorials folder

**Comment by icq4ever** [comment]
@arturoc @tado great! and of course I want! :+1:

**Comment by ofZach** [comment]
thanks !!  one thing to note at the howTos are sometimes changing (and many more will be coming in) -- 
sometimes the changes involve just reorganizing material, editing, etc, but good to keep your eye out for those changes.  I've been doing some inline editing to fix things and it looks like arturo is doing the same.

**Comment by arturoc** [comment]
but yes now that it's starting better to keep an eye, perhaps we could add something to signal that a document has changed since the translations were written, perhaps we can check the dates for every language and show if the original has changed or something like that

in any case, as i see it, this more dynamic sections will probably evolve differently in the different languages, someone might create a how to in korean that doesn't exists in english, someone might translate it later to english or not.

**Comment by edap** [comment]
We could also use a git post-commit hook, thats checks if the date of the english file is newer than the korean/japanese one, and, if yes, add the name of the file in list.txt file containing all the articles that are not in sync.

**Comment by arturoc** [comment]
yes i was thinking about something like that but that would appear in the web itself in each article so people reading an article would now if it's up to date or there's a newer version in the original

**Comment by arturoc** [comment]
i've marked the translated articles which have a newer original with an asterisk in the home page. there's a legend at the bottom that explains what the * is. it's useful and it shows really quick which articles need to be updated but don't like too much how it looks so if any one has a better idea about the layout...

@edap the problem with generating a different file is that it would had to be committed and pushed by the script itself, also people would have to check the file explictly from time to time, having it in the web makes it easier for anyone to spot it and renew the translation.

i'll also add a link to edit in github inside the how tos

**Comment by icq4ever** [comment]
@arturoc great idea. that's simple and clear.

**Comment by icq4ever** [comment]
@arturoc for translating ofBook contents, do I need to fork ofBook repository?

**Comment by arturoc** [comment]
goint to close this since the details on how to do it seem clear now

**Comment by arturoc** [comment]
@icq4ever yes in principle i'd say that should go in the book repo but let me check first with the people who has done the book design... so we don't do it in a way that could break their workflow.

**Comment by icq4ever** [comment]
@arturoc ok. got it.
