### ISSUE TITLE
design / css changes for how-tos ?

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofSite#485]
the following things seems like small fixes for the "how to" css that will help legibility.

<img width="1122" alt="screen shot 2016-02-21 at 5 59 10 am" src="https://cloud.githubusercontent.com/assets/142897/13202692/9494abf6-d860-11e5-8f07-a0847218a86e.png">

a) smaller header (the header here is really large) maybe we can use h2 instead of h1? or adjust in css?
b) more padding between header and back button
c) smaller content margin to make text easier to read

**Comment by sh0w** [comment]
yes, great idea!
(we were also talking with caitlin yesterday that it would be nice to have the how-tos in a sidebar on the how-to detail page, that would also make the content section less wide and easier to read)
