### ISSUE TITLE
outdated meetup groups

### ISSUE THREAD

**Issue by sh0w** [openframeworks/ofSite#488]
http://openframeworks.cc/community/ -> "recurring meetups"
all of these except nyc and seattle are outdated :(

**Comment by arturoc** [comment]
yeah, nobody ever maintained this, we should probably just remove it, if there was a way to have something more dinamic like create a section in the forum specific for this kind of events and then pull this section dynamically from there using js that would work better i guess.

In any case i would remove it by now
