### ISSUE TITLE
localized css?

### ISSUE THREAD

**Issue by arturoc** [openframeworks/ofSite#499]
@icq4ever @tado @KavinHan would it help if we added a specific css per language? that way you could control the font type for your languages or change some sizes... if things don't fit very well with the default style

**Comment by tado** [comment]
@arturoc There is no problem for Japanese site!

**Comment by icq4ever** [comment]
@arturoc at the moment no big issue. but if I found that, I'll let you know! thanks!

**Comment by arturoc** [comment]
ok, going to close this then but let me know if you need it some time should be pretty straight forward to add
