### ISSUE TITLE
301 errors 

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofSite#500]
as pointed out by grayfuse in slack 

> Coworker just came across this. With the top-level taxonomy changing (tutorials moved to learning), google’s long-time indexing of the tutorials folder is leading to some 404s. Can we get setup a catch-all 301 redirect for that page? I’m happy to do the PR if someone who manages ofSite can point me in the right direction.

![google-search-results](https://cloud.githubusercontent.com/assets/142897/13259439/f943cd44-da1c-11e5-809a-3445619cd997.png)

**Comment by arturoc** [comment]
Just fixed it, there's really no way to do this with a PR, the latest config for the webserver is here: https://github.com/openframeworks/ofSite/blob/master/utils/nginx.conf  but that won't work only by changing the file in the repo. the easiest is to go into the server change the config there to be able to test it and then bring back that file to the repo so next time we have to install it we have the last version.

anyway it's fixed now, i've redirected everything from tutorials* -> learning

i've heard that book is coming out soon :)

**Comment by ofZach** [comment]
Thanks for fixing it :) one book at a time

**Comment by grayfuse** [comment]
Kickass!
