### ISSUE TITLE
add cheat sheet to learning

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofSite#510]
this new 0.9 cheat sheet seems really helpful

https://forum.openframeworks.cc/t/of0-9-cheat-sheet/22581

maybe we can link to this off the learning page?  what do you think @sh0w ?

**Comment by sh0w** [comment]
yes, this is fantastic. it should definitely be featured on the learning
page!

i'm happy to add it - but where?  "getting started" or "external
resources"?

**Comment by icq4ever** [comment]
I'll give 1 point to "external resources"!

**Comment by arturoc** [comment]
added a link to this in the wiki
