### ISSUE TITLE
remove non real how-tos

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofSite#513]
I think this was done just to see how to do groupings but it's probably a good idea to remove anything that isn't real.  I just saw this tweet : 

<img width="274" alt="screen shot 2016-03-02 at 5 45 55 pm" src="https://cloud.githubusercontent.com/assets/142897/13478382/cdfe4e88-e09e-11e5-8018-92cc04c83175.png">

about this one for example: 

http://openframeworks.cc/learning/06_events/event_example_how_to/

**Comment by edap** [comment]
@ofZach  that one was added some day ago http://openframeworks.cc/learning/06_events/event_example_how_to/

The only "how to" that is missing is this one: http://openframeworks.cc/learning/07_network/network_example_how_to/
I think it's ok to leave it there, we can easily remember that it needs to be done.
I think this issue can be closed now.
