### ISSUE TITLE
"Getting your Raspberry Pi ready for openFrameworks" out of date

### ISSUE THREAD

**Issue by cgiles** [openframeworks/ofSite#516]
In the page : http://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/ the link : curl -O http://openframeworks.cc/versions/v0.9.2/of_v0.9.2_linuxarmv6l_release.tar.gz is out of date, the 0.9.3 being available.

**Comment by arturoc** [comment]
thanks it's fixed now
