### ISSUE TITLE
Documentation problem in ofGLProgrammableRenderer

### ISSUE THREAD

**Issue by RebelMoogle** [openframeworks/ofSite#521]
The link to the shader tutorial links to the tutorial overview which does not include the shader tutorials anymore. 

Also might be good to link to the following blog post instead, since it more accurately describes the current usage: http://blog.openframeworks.cc/post/133400454159/openframeworks-090-opengl-45

**Comment by arturoc** [comment]
that tutorial is now part of the book, here: http://openframeworks.cc/ofBook/chapters/openGL.html

do you want to send a pull request to change the link? you can do show pressing the button to edit the class at the beginning of the docs

**Comment by RebelMoogle** [comment]
Hope that looks ok, that would be my first real pull request. :)

**Comment by edap** [comment]
@RebelMoogle welcome!
