### ISSUE TITLE
image links are broken in `how to contrubuting to document`

### ISSUE THREAD

**Issue by icq4ever** [openframeworks/ofSite#525]
check [english page](http://openframeworks.cc/documentation/contributing/)and [korean page](http://openframeworks.cc/ko/documentation/contributing/)

I wanna trying move image to somewhere, but document directory is not proper way.

**Comment by arturoc** [comment]
thanks didn't noticed it before. just fixed it. i've also removed the part that was still refering to the old web system. i've removed it to from the korean translation, i think it's correct but if you can take a look just in case?
