### ISSUE TITLE
:: (colon colon) breaks the parser

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/ofSite#53]
see `ofDirectory::getFile(...)` in `ofFileUtils.h`, which has 3 arguments -- but it only shows 2.

**Comment by tpltnt** [comment]
Is this still an issue? The example mentioned by @kylemcdonald shows 3 parameters, therefore i would like to see this issue closed.

**Comment by kylemcdonald** [comment]
thanks @tpltnt it does look like it's fixed! it's also not a problem in @halfdanj's work either http://docs.openframeworks.cc/ofFileUtils.html

closing.
