### ISSUE TITLE
Community Page Updates

### ISSUE THREAD

**Issue by mikechambers** [openframeworks/ofSite#533]
I would like to get more involved in contributing to the docs and website for OF. I was going to start by doing a pass at updating the community page at:

http://openframeworks.cc/community/

Does anyone see any issues with this? or have any comments / suggestions? (I have some ideas).

Also, I apologize if this is not the correct place to ask, but I have not had any luck on getting any responses on the IRC forum, and am still waiting to be added to the of-dev list.

Assuming this is ok, I have some follow up questions. There are quite a few references to "Community Mailing List" on the website, all of which point to:

http://openframeworks.cc/list-info/

However, that page does not reference any mailing list, and I cant find any reference on google. Does this list still exist? Is this supposed to the of-dev list?

Where is the best place to discuss documentation / website issue? Via github issues? Somewhere else?

Thanks..

**Comment by edap** [comment]
Hello @mikechambers, there is this slack URL https://ofslack.herokuapp.com/, there are some channels dedicated to the docs.

**Comment by mikechambers** [comment]
@edap Thanks! Ill hop on slack.

**Comment by mikechambers** [comment]
ok. Chatted in the slack room. It looks like the mail list refers to the dev list.

I am going to do a pass on updating the page, removing / fixing broken links, and adding new links to highlight the community, and direct people to the core community areas.

**Comment by mikechambers** [comment]
About 2 months ago I submitted a pull request for a complete update of the site's community page. Aftter some suggestions and tweaks the request was accepted.

How often is the site updated? I am interested in contributing more to the project / site, but to be honest, I don't want to waste my (or anyone else) time.

Any eta on when the new changes will be reflected on the site?

**Comment by edap** [comment]
Hello @mikechambers, in my experience, after a PR is merged the website is deployed and your changes are live on production, I don't know if the merge trigs the deploy automatically or if the website is deployed once a day. But if your PR was merged 2 months ago and the page you edited is not on the website, i assume smth went wrong. Maybe @arturoc has more information about the deployment process

**Comment by edap** [comment]
Hello @mikechambers, did you solve this problem?
Maybe it is a stupid question, but can you see your changes locally?
