### ISSUE TITLE
Broken Edit Class Link in ofImage docs

### ISSUE THREAD

**Issue by mikechambers** [openframeworks/ofSite#547]
http://openframeworks.cc/documentation/graphics/ofImage/#show_getColor

Link for Edit Class points to:
https://github.com/openframeworks/ofSite/edit/master/documentation/graphics/ofImage.markdown

which is 404.

I think it should point to:
https://github.com/openframeworks/ofSite/blob/master/documentation/graphics/ofImage_.markdown

**Comment by javl** [comment]
The current link has `ofImage.markdown` at the end, which should be `ofImage_.markdown` (note the underscore). The same is true for `ofPixels_` and `ofColor_`, as do some addons such as `ofxVecSlider_`.

Not sure how to change this in the code, as the template uses `${clazz.name}.markdown` and adding the underscore would add this for all classes.
