### ISSUE TITLE
Notes about setup/android-eclipse in Ubuntu 16.04

### ISSUE THREAD

**Issue by sejomagno** [openframeworks/ofSite#553]
Hi!
I'm following the [guide to setup Android with Eclipse](http://openframeworks.cc/setup/android-eclipse/) in my Ubuntu 16.04 installation. I've found some issues with Eclipse and their corresponding solutions in the Internet. I don't know if I should add them (and where) into the guide.
- Step j)
  - Problem: Eclipse Preferences window does not work
  - Fix: [Ubuntu 16 LTS - Eclipse window preferences not working properly](http://stackoverflow.com/questions/36827762/ubuntu-16-lts-eclipse-window-preferences-not-working-properly)
- Step j)
  - Problem: There's neither Android button in the Eclipse toolbar, nor Android SDK Manager menu under Window
  - Solution: [http://stackoverflow.com/questions/4649562/eclipse-with-android-sdk-missing-menu-items](http://stackoverflow.com/questions/4649562/eclipse-with-android-sdk-missing-menu-items)

**Comment by arturoc** [comment]
Closing since eclipse is not supported any more
