### ISSUE TITLE
ofBook urls is seeming to point back to the homepage

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofSite#559]
see for example 

http://openframeworks.cc/ofBook/chapters/animation.html

**Comment by bakercp** [comment]
@arturoc This is a critical issue as classes are starting in the next few days for some ... any way I can help get it back online? @mikewesthad

**Comment by mikewesthad** [comment]
I'm not really sure how the book is hosted on the site. Is this an issue specific to the animation link?  That's the only one that I could find that had this issue.  Maybe that's a clue.

**Comment by bakercp** [comment]
It seems that this is back online now ... ? http://openframeworks.cc/ofBook/chapters/foreword.html

**Comment by bakercp** [comment]
Well, now, this seems to be happening again .. but only with some of the links from the learning page.

http://openframeworks.cc/ofBook/chapters/version_control_with_git.html

but this one does work ...

http://openframeworks.cc/ofBook/chapters/foreword.html

and this one doesn't ...

http://openframeworks.cc/ofBook/chapters/animation.html

**Comment by ofZach** [comment]
hmm sidebar is missing from that -- that's a clue. 

ok here's my theory -- the book building is failing somewhere, since the sidebar is missing and I feel like later chapters aren't getting built. 

the way the book gets built, it builds chapter by chapter and then after, adds the sidebar to all the pages.  

often times the book building will fail on esoteric things like latex commands.  I've noticed that the python on the server can be a little different compared to osx so I remember having to make some fixes, perhaps something got updated or needs adjustment in the script ?

I usually try to build locally and if that works and then log into openframeworks and build there (which is that the commit hook does).  I am currently traveling but can take a look early next week.

**Comment by ofZach** [comment]
so sorry just have time to check this now,  appears something got misconfigured on the server...  taking the conversation to email for a sec...

**Comment by tpltnt** [comment]
The links listed here all seem to work (as of 2016-10-29). Are there more problems or can this issue be closed?

**Comment by ofZach** [comment]
this came down to needing to reinstall some python modules on the server...  closing this issue.
