### ISSUE TITLE
Add https support on all openframeworks.cc domains.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/ofSite#575]
This is fairly straight-forward and free now with https://letsencrypt.org/.

**Comment by arturoc** [comment]
this is already setup in the forum where people have to enter passwords and there might be more personal info, we could do it in the OF site too but i don't think it's a huge advantage.

**Comment by bakercp** [comment]
All sites should be secure.

- https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
- https://arstechnica.com/information-technology/2017/01/firefox-chrome-start-calling-http-connections-insecure/

etc.

**Comment by bakercp** [comment]
- https://security.googleblog.com/2017/04/next-steps-toward-more-connection.html?m=1
- https://blog.malwarebytes.com/101/2017/09/google-reminds-website-owners-to-move-to-https-before-october-deadline/

**Comment by arturoc** [comment]
the main site is now also under https to protect the donations system
