### ISSUE TITLE
Documentation problem in ofGraphics

### ISSUE THREAD

**Issue by hinike** [openframeworks/ofSite#580]
I use this code,but I get a thick line
ofSetLineWidth(400.0f);
	
ofDrawLine(ofGetMouseX(), ofGetMouseY(), ofGetMouseX() + xOffset, ofGetMouseY() + yOffset);

**Comment by arturoc** [comment]
there's a limitation on the line width, this depends on the graphics driver you can check it with:

```
GLfloat lineWidthRange[2];
glGetFloatv(GL_ALIASED_LINE_WIDTH_RANGE, lineWidthRange);
cout << "min line width: " <<  lineWidthRange[0] << " max: " lineWidthRange[1] " << endl
```

if you need something thicker than that you'll need to draw a rectangle or create the specific shape using fro example an ofPath
