### ISSUE TITLE
ofMesh.markdown: normal index matching face index?

### ISSUE THREAD

**Issue by hamoid** [openframeworks/ofSite#583]
Some examples suggest the normals are per-vertex, but the documentation might suggest they are per-face:

> you need to make sure you add normals at the same index of the matching face.

Should this be "at the same index of the matching vertex"?

**Comment by arturoc** [comment]
yes normals are always per vertex. if you want to send a PR?

**Comment by hamoid** [comment]
Sure :)

**Comment by hamoid** [comment]
Done at https://github.com/openframeworks/openFrameworks/pull/5427

**Comment by hamoid** [comment]
Closing, as the pr was merged.
