### ISSUE TITLE
Documentation problem in ofAppGLFWWindow

### ISSUE THREAD

**Issue by ge53** [openframeworks/ofSite#585]
i have tried compiling examples in both of_0.9.6 and of_0.9.8--can't run anything due to this error (see attached) running Windows10 and Visual Studio15--Any help/suggestions appreciated ...
![screen](https://cloud.githubusercontent.com/assets/12898784/22837311/f6a64d6e-ef8d-11e6-8454-c12080896a52.JPG)

**Comment by ofZach** [comment]
it seems like it's an issue with glfw -- I wonder if it's related to this

https://github.com/glfw/glfw/issues/471

can you look in device manager and see what your display looks like?

**Comment by ge53** [comment]
genius! the monitor said 'turned off'
Thank you!
