### ISSUE TITLE
Documentation problem in ofXml

### ISSUE THREAD

**Issue by cgiles** [openframeworks/ofSite#586]
for the function setValue, the example mentions a function setPath : http://openframeworks.cc/documentation/utils/ofXml/#show_setValue

**Comment by javl** [comment]
This seems to be part of a bigger 'problem', as ofXml doesn't seem to have a `setPath()` nor a `setValue()` method?
Seems `setValue()` is part of ofXmlSettings (but that method creates a single tag, not an entire pat as show in the example code) and it's also part of `ofxXmlPoco` which does not have it's own documentation (not sure if it's meant to use directly).
