### ISSUE TITLE
Can't login with GitHub account

### ISSUE THREAD

**Issue by juschu** [openframeworks/ofSite#594]
I tried to sign up on `forum.openframeworks.cc` with my GitHub Account. I was already logged in on GitHub and after I clicked the button to sign up with GitHub I just saw this error message:

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

Then I tried it again after logging out from GitHub and also in the private mode of my browser. Thy only thing that changed was, that I had to enter my username and password but I still git the same error message.
The URL where I saw the error message is `https://forum.openframeworks.cc/auth/failure?message=redirect_uri_mismatch&origin=https%3A%2F%2Fforum.openframeworks.cc%2F&strategy=github`

The first time I tried it I click Log In and not Sign Up. After that I only clicked on Sign Up.

**Comment by arturoc** [comment]
can you try if it's working now?

**Comment by juschu** [comment]
Yes, now it's working.
I already created an account before just with my e-mail and didn't create a new one now. But now I got past the point where it didn't worked before and stopped at the point where I could enter a new username and password.

**Comment by arturoc** [comment]
great thanks!
