### ISSUE TITLE
Android nightly is not listed.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/ofSite#603]
It's not listed on the page 

![download___openframeworks](https://cloud.githubusercontent.com/assets/300484/26365399/1f4c119e-3fad-11e7-871c-dcac9f1e587a.png)

but it shows up here ...

![index_of__versions_nightly_](https://cloud.githubusercontent.com/assets/300484/26365373/105289de-3fad-11e7-9897-6b98824be646.png)

**Comment by javl** [comment]
It seems this is a part of the website that is not in the repo? Can't seem to find the file at http://ci.openframeworks.cc/nightlybuilds.html in the repo.

**Comment by javl** [comment]
What I meant was that it seems that part of the website (with the text `Here you can find a daily build`) is not found in the Github repository but only stored somewhere else online. But you're right, the Android link is there so no problem.

**Comment by arturoc** [comment]
Yes that's inserted as an iframe from the server that generates the nightly builds every night
