### ISSUE TITLE
ofQuaternion operator*

### ISSUE THREAD

**Issue by dno89** [openframeworks/ofSite#622]
Hi,
I came across the composition of rotation with quaternion multiplication. From the results I had and checking the code it appears that the multiplication operator* actually implements the inverse multiplication (swapping the factors).
Is there a rationale for this?
Thanks

**Comment by arturoc** [comment]
The only rationale is that the library we took the original code from worked with that multiplication order. it's the same for matrices and vectors too.

From 0.10 (the current nightlies and code in github) we include glm for vector math where the multiplication order is the opposite and will slowly deprecate the current vector math classes
