### ISSUE TITLE
Fix all broken links in /documentation

### ISSUE THREAD

**Issue by hamoid** [openframeworks/ofSite#634]
We can find all broken links at once.

WARNING: SLOW. To avoid producing CO2, please DON'T click this link unless you plan to fix those links :) https://validator.w3.org/checklink?uri=http%3A%2F%2Fopenframeworks.cc%2Fdocumentation%2F&hide_type=all&recursive=on&depth=5&check=Check

After a few minutes, all pages are checked. Then we can search for `404 Not` in the results in that same page to find all the broken _target_ links. Then we scroll up a little bit, to find in which page the link is found. Some pages like ofGLRenderer have many links pointing to non existing pages with .html extension.

**Comment by arturoc** [comment]
that's really nice but i believe is producing a ton of false positives. all the functions in the docs are being reported as not linked but they are really working. i believe it's because we use javascript to produce those links but not sure.

**Comment by hamoid** [comment]
The result page shows tons of results, and most can be ignored. But if you search for `404 Not` on that page I think you find real broken links. I see 16 sections with broken 404s.

One of them is ofGLRenderer. If you see http://openframeworks.cc/documentation/gl/ofGLRenderer/#show_popMatrix it contains a broken link to http://openframeworks.cc/documentation/gl/ofGraphics.html#show_ofPopMatrix . At least for me it's broken, and I think it should be replaced with http://openframeworks.cc/documentation/graphics/ofGraphics/#!show_ofPopMatrix instead (gl -> graphics, replace `.html#` with `/#!`). Many pages inside ofGLRenderer have the same broken "see x" link. Side note: I wanted to add such links also to the other renderers, which are missing the "see x" link completely.

**Comment by arturoc** [comment]
ah ok yeah that makes sense. that's really useful.
