### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by kr15h** [openframeworks/ofSite#649]
Travis CI could not deal with the certificates for whatever reason. Output below.

```
converted 'http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz' (ANSI_X3.4-1968) -> 'http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz' (UTF-8)
--2018-05-08 08:33:03--  http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz
Resolving openframeworks.cc (openframeworks.cc)... 23.253.221.243
Connecting to openframeworks.cc (openframeworks.cc)|23.253.221.243|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz [following]
converted 'https://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz' (ANSI_X3.4-1968) -> 'https://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz' (UTF-8)
--2018-05-08 08:33:03--  https://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz
Connecting to openframeworks.cc (openframeworks.cc)|23.253.221.243|:443... connected.
ERROR: The certificate of 'openframeworks.cc' is not trusted.
ERROR: The certificate of 'openframeworks.cc' hasn't got a known issuer.
```

**Comment by arturoc** [comment]
where is this output from?

**Comment by kr15h** [comment]
From my Travis Configuration here: 
https://travis-ci.org/kr15h/openframeworks-rpi-image

I am re-running now to see if it is there still.

**Comment by kr15h** [comment]
Should update to 0.10.0 anyway : ]

**Comment by kr15h** [comment]
It is there still. I am trying to work with the archive of 0.9.8, is it still there? Maybe that is the issue- should I change the URL to it?

**Comment by arturoc** [comment]
i think the link is correct. probably the issue is that ci runs on pretty old machines that still don't have the letsencrypt certificate you might need to add it manually with a script during the install phase

**Comment by kr15h** [comment]
Weird, I can download it via Chrome directly, but Travis gives me certificate error. Maybe someone has to go to Rigaer Strasse and knock at the door.

**Comment by kr15h** [comment]
Yes, will try that. Did you regenerate the certificate recently?

**Comment by arturoc** [comment]
i just added it yesterday the certificate is fine. also if you are downloading with wget you can use --no-check-certificate to skip the certificate check

**Comment by kr15h** [comment]
oh, ok, will try this one. thanks!

**Comment by kr15h** [comment]
It works!
