### ISSUE TITLE
Documentation - Research broken

### ISSUE THREAD

**Issue by CyrCom** [openframeworks/ofSite#659]
To reproduce:
[https://openframeworks.cc/documentation/](https://openframeworks.cc/documentation/)
(type something and hit enter)

I’m on firefox and it seems that “part of the page was not ‘hashed’ before transmitting”
This is considered as unsecured content, if I disable the protection, it actually works.

**Comment by javl** [comment]
If this gets fixed, this might solve #616 as well.

**Comment by dimitre** [comment]
It is not working again, I think it is the usual certificate issues.

**Comment by arturoc** [comment]
should be working again. if you still get an error try refreshing the page with ctrl + shit + r or cmd + shift + r in macos so it fully reloads instead of reading from the cache
