### ISSUE TITLE
RaspberryPi setup guide - update for Raspberry PI 3?

### ISSUE THREAD

**Issue by periode** [openframeworks/ofSite#669]
The current setup guide says that you should download v0.9.8 but this version is no longer supported by the latest release of Raspbian (Stretch).

https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/

```
cd
wget https://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz
mkdir openFrameworks
tar vxfz of_v0.9.8_linuxarmv6l_release.tar.gz -C openFrameworks --strip-components 1
```

Overall, the page is for setting up OF on a RPI running Jessie, so maybe we should update it for Stretch as a default? Happy to do it!

**Comment by icq4ever** [comment]
due to that setup guide is updated, I'll close this issue. 
thanks.
