### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by cjdg** [openframeworks/ofSite#671]
I cant access website, it appears with the following code: 

error: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by ofZach** [comment]
seeing this also -- 

cc @arturoc I think this is related to the change to https 

https://github.com/openframeworks/ofSite/issues/575

**Comment by sgnm** [comment]
@ofZach
Cc: @arturoc

When I try to open ofSite I got a below error message.
> NET::ERR_CERT_DATE_INVALID

In detail, Google said that ofSite's security certificate expired 3 days ago.
Could you check it?

**Comment by arturoc** [comment]
this is solved now

**Comment by sgnm** [comment]
Thank you @arturoc 🙏
