### ISSUE TITLE
Documentation problem in ofFbo

### ISSUE THREAD

**Issue by bbogart** [openframeworks/ofSite#680]
On this page: https://openframeworks.cc/documentation/gl/ofFbo/#show_readToPixels

This text:

> 
> readToPixels(...)
> void ofFbo::readToPixels(ofFloatPixels &pixels, int attachmentPoint=0)
> 
> This allows you to get the pixels from an ofFbo and store it in an ofShortPixels instance. The attachmentPoint parameter allows you indicate which of the textures attached to the fbo you want to grab. The ofShortPixels instance is useful when you want your image as floating point values.

Should probably read like so:

> readToPixels(...)
> void ofFbo::readToPixels(ofFloatPixels &pixels, int attachmentPoint=0)
> 
> This allows you to get the pixels from an ofFbo and store it in an ofFloatPixels instance. The attachmentPoint parameter allows you indicate which of the textures attached to the fbo you want to grab. The ofFloatPixels instance is useful when you want your image as floating point values.

**Comment by arturoc** [comment]
thanks!
