### ISSUE TITLE
Problem with Windows installation guide, + FIX

### ISSUE THREAD

**Issue by golanlevin** [openframeworks/ofSite#688]
As of January 2019, the OF Windows installation guide has some significant errors and omissions which prevent a new user from being able to get OF up and running. I'm referring to the page at: [https://openframeworks.cc/setup/vs/](https://openframeworks.cc/setup/vs/)

**1. Outdated link to OF plugin** 
The link to the OpenFrameworks Visual Studio plugin is out of date and incorrect. Currently the setup guide links to [https://marketplace.visualstudio.com/items?itemName=ArturoCastro.openFrameworksplugin](https://marketplace.visualstudio.com/items?itemName=ArturoCastro.openFrameworksplugin), which is for the plugin that works with Visual Studio **2015**. 

_Instead_, the page should link here, which is the version of the plugin that works with Visual Studio Community 2017: [https://marketplace.visualstudio.com/items?itemName=HalfA.openFrameworkspluginforVisualStudio2017](https://marketplace.visualstudio.com/items?itemName=HalfA.openFrameworkspluginforVisualStudio2017)

**2. Documentation currently missing for necessary additional VS components**
A number of additional VS components must be installed in order to develop with OF in Windows. As near as we can determine, there is no documentation of this fact. Below is a screenshot of the components that need to be installed. This list was debugged by, and courtesy of, @CharStiles: 

![visual studio installer 24_01_2019 12_36_25](https://user-images.githubusercontent.com/290053/51855112-68fb9f80-22fa-11e9-8320-136b30a094f0.png)

Thanks for your attention!
<3 Golan

**Comment by arturoc** [comment]
Thanks Golan and @mikechambers 

Just updated the guide with the link and this image.

@tado @icq4ever Could you do this change in the Japanese and Korean guides?

Thanks!

**Comment by arturoc** [comment]
This is the commit: https://github.com/openframeworks/ofSite/commit/3bd9153f75a38cd707736c1d9d02bcf90ad0b9f6

**Comment by tado** [comment]
Sure!

**Comment by icq4ever** [comment]
update :)  and thank you @golanlevin.

**Comment by tado** [comment]
finished! https://github.com/openframeworks/ofSite/commit/464c5cc1f021ce48341c85897272bc1e1b36b093

**Comment by tado** [comment]
Oh, the path of the image is not correct. Now fixed.

>

**Comment by icq4ever** [comment]
@tado thanks to notice that! :$

**Comment by arturoc** [comment]
thanks!
