### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by TheInnerParty** [openframeworks/ofSite#696]
The main openframeworks website's certificate seems to have expired today, which is preventing it from loading on any of the major web browsers: 
![Screen Shot 2019-06-01 at 7 17 51 PM](https://user-images.githubusercontent.com/12105502/58755895-0aaa1d80-84a2-11e9-81f5-76eb55ef4f84.png)

**Comment by arturoc** [comment]
it's solved now. thanks!

**Comment by dimitre** [comment]
Certificate expired again
