### ISSUE TITLE
Text error on the Community page

### ISSUE THREAD

**Issue by EdwardDeaver** [openframeworks/ofSite#713]
Hello,

There is a text error on the community page. 
 
Community page: https://github.com/openframeworks/ofSite/blob/822d7e0f28c3b5bb69141de13d69946ce9353982/content/community.md

In the Code of Conduct section, first sentence: "diverse backgrounds po를ssible". 

The "를" should be removed.

**Comment by icq4ever** [comment]
thanks to let know. it was my mistake.  :$
