### ISSUE TITLE
Rpi Buster / oF 0.11.0 update has wrong info about the X11 Desktop?

### ISSUE THREAD

**Issue by sourya-sen** [openframeworks/ofSite#725]
The setup guide still reads for the Raspberry Pi

```
openFrameworks does not use the X11 Desktop for running OF applications. You can save GPU memory by disabling it. This is optional but suggested.

0. Select `3 Boot Options`
0. Select `B1 Console` or `B2 Console Autologin`
```

Which is not true anymore - right?

@ofTheo shouldn't this be removed and/or the windowing system with GLFW be mentioned somehow?

**Comment by ofTheo** [comment]
oops - I missed that! 
Thanks.  GLFW is mentioned a bit lower on the page: https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/

**Comment by ofTheo** [comment]
Thank you - this is now fixed and should update on the site shortly! 
https://github.com/openframeworks/ofSite/commit/c6700820be66245158a0dd6dcf6bc8f897dd682f
