### ISSUE TITLE
Can't access to: C and C++ in 5 days by Philip Machanick 

### ISSUE THREAD

**Issue by EkremDincel** [openframeworks/ofSite#728]
I can't access too this link: http://www.itee.uq.edu.au/~comp3300/Resources/C_C++_notes.pdf
Above link redirects me to this: https://auth.uq.edu.au/idp/module.php/core/loginuserpass.php

The position of the link in the site (as header):
openframeworks.cc/about/faq/How can I learn C++?

How can I access to this PDF?

**Comment by chrisbolin** [comment]
this should work for you: http://doc.gold.ac.uk/~mus02mg/creativecomputation/wp-content/uploads/c-5days.pdf

**Comment by EkremDincel** [comment]
Thanks!
