### ISSUE TITLE
404 for Windows QT Creator Downloads

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/ofSite#749]
Just tried downloading the 32 bit and 64 bit qtcreator packages for windows and they both 404.

**Comment by ofTheo** [comment]
Oops yeah!
Not sure why those didn't generate. Will make them. 

There was not really any difference for msys2 between 0.11.1 and 0.11.2 so you can use 0.11.1 in the meantime:
https://openframeworks.cc/versions/v0.11.1/ 

Apologies!!

**Comment by ofTheo** [comment]
Thanks @neilmendoza I think I manually copied them over for 0.11.1, but fixed it in the ofSite script now.
