### ISSUE TITLE
Documentation problem in ofGraphics

### ISSUE THREAD

**Issue by Jade570** [openframeworks/ofSite#750]
There is typo issue in ofDrawRectangle() ([link here](https://openframeworks.cc//documentation/graphics/ofGraphics/#!show_ofDrawRectangle)).

The example code snippet for 
`void ofDrawRectangle(float x1, float y1, float w, float h)`
in the site currently is written as:
```
void ofApp::draw(){
    ofDrawRect(10,10,100,100);
}
```

This should be corrected to

```
void ofApp::draw(){
    ofDrawRectangle(10,10,100,100);
}
```

**Comment by icq4ever** [comment]
https://github.com/openframeworks/ofSite/commit/a046ebc4fbe8e0836ee2a4b19be21a7b135c2ec1

thanks!
