### ISSUE TITLE
development, links to IRC and of-dev mailing list

### ISSUE THREAD

**Issue by dimitre** [openframeworks/ofSite#788]
I am seeking information about openFrameworks development in this section
https://openframeworks.cc/development/
and it mentions IRC and of-dev mailing list, are they still relevant? I think mailing list link is actualy broken, and IRC enters on channel #freenode. 
Thanks

**Comment by ofTheo** [comment]
@dimitre the mailing list is pretty non active so we could remove that link. IRC also. 
The OF slack is active - so we should add a link to that.

**Comment by dimitre** [comment]
Nice, I can make a PR soon. Slack link is https://ofslack.herokuapp.com right?

**Comment by ofTheo** [comment]
Yes! Thanks!!

**Comment by dimitre** [comment]
Done! https://github.com/openframeworks/ofSite/pull/789
