### ISSUE TITLE
Documentation problem in ofImage

### ISSUE THREAD

**Issue by macginitie** [openframeworks/ofSite#818]
the asterix multiplication symbol is being interpreted as italics indicator here:
![Screen Shot 2024-01-03 at 10 55 11 PM](https://github.com/openframeworks/ofSite/assets/40873334/152d0303-ce95-45ec-be4a-e2af640e66da)

**Comment by dimitre** [comment]
can you please submit a pull request to fix it? thanks

**Comment by macginitie** [comment]
https://github.com/openframeworks/ofSite/pull/819 <== I hope that will work

**Comment by dimitre** [comment]
Thank you, PR merged. 
we can check here later to see if it propagate
https://openframeworks.cc/documentation/graphics/ofImage/#show_getPixels

@ofTheo does the server get the latest from master from time to time?

**Comment by macginitie** [comment]
lol, I read too much Asterix the Gaul as a youth -- the word is asterisk! Thanks :) seems like it worked from what I see.

**Comment by dimitre** [comment]
ofSite / documentation is one area that needs some energy, 
Corrections and improvements are welcome, thank you

closed by https://github.com/openframeworks/ofSite/pull/819
