### ISSUE TITLE
Documentation problem in ofTrueTypeFont

### ISSUE THREAD

**Issue by SemanticZeus** [openframeworks/ofSite#827]
The return type should be std::vector<ofPath> not an int.

**Comment by ofTheo** [comment]
Thanks @SemanticZeus 
Can you link / point to the line - or submit a Pull Request to fix it?

**Comment by SemanticZeus** [comment]
Hi. thank you for your quick response. I just created a pull request.
https://github.com/openframeworks/ofSite/edit/master/documentation/graphics/ofTrueTypeFont.markdown
this is the link to the document.
the return value of the function getStringAsPoints() should be a std::vector<ofPoint>, not an int.

**Comment by ofTheo** [comment]
Thanks so much!
Closed by #828
